repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0 # Use a specific version for consistency
    hooks:
      - id: black
        language_version: python3 # Or the